# Variable Group 'grocery-list' was defined in the Variables tab
variables:
  - group: grocery-list
  - name: buildTag
    value: $(Build.SourceBranchName).$(Build.BuildId)
  - name: BuildParameters.dockerFile
    value: '**/Dockerfile'
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isDevOps
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/devops/')]
  - name: isPR
    value: $[eq(variables['Build.Reason'], 'PullRequest')]

trigger:
  branches:
    include:
    - refs/heads/main

resources:
  repositories:
  - repository: self
    type: git

  pipelines:
  - pipeline: grocery-shop-ui
    source: grocery-shop-ui
  
name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
  
stages:

- stage: Test_Build
  condition: and(eq(variables.isPR, 'true'), eq(variables.isMain, 'false'))
  displayName: 'Run build image'

  jobs:
  - job: Build
    displayName: Build job
    pool: Default

    steps:
    - checkout: self

    - task: Docker@0
      displayName: Build an image
      inputs:
        action: Run a Docker command
        dockerFile: $(BuildParameters.dockerFile)
        customCommand: build --target build -t gr-list-test .

    - task: Docker@0
      displayName: Clean unuses images
      inputs:
        action: Run a Docker command
        customCommand: image rm gr-list-test -f

- stage: Build_N_Push
  condition: eq(variables.isMain, 'true')
  displayName: 'Run build and push image to ACR'

  jobs:
  - job: Build
    displayName: Build_N_Push job
    pool: Default

    steps:
    - checkout: self

    - task: Docker@0
      displayName: Build an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        dockerFile: $(BuildParameters.dockerFile)
        imageName: grocery-shop-ui
        additionalImageTags: $(buildTag)

    - task: Docker@0
      displayName: Push an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        action: Push an image
        imageName: grocery-shop-ui
        additionalImageTags: $(buildTag)

    - task: Docker@0
      displayName: Clean unuses images
      inputs:
        action: Run a Docker command
        customCommand: image rm grocery-shop-ui:$(buildTag) -f

    - task: Docker@0
      displayName: Clean dangling images
      inputs:
        action: Run a Docker command
        customCommand: image prune -f

- stage: Deploy2dev
  dependsOn: Build_N_Push
  condition: and(succeeded('Build_N_Push'), eq(variables.isMain, 'true'))
  displayName: Deploy to AKS dev

  jobs:

    - job: Deploy
      displayName: Deploy to dev-AKS job
      pool: Default
      
      steps:
      - checkout: self
      
      - task: KubernetesManifest@0
        displayName: deploy
        continueOnError: false
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'grocery-list-dev-sc'
          namespace: 'grocery-list-dev'
          manifests: manifests/dev-deployment.yml
          containers: mddinternship2021h2project.azurecr.io/grocery-shop-ui:$(buildTag)

- stage: Deploy2demo
  dependsOn: Deploy2dev
  condition: and(succeeded('Deploy2dev'), eq(variables.isMain, 'true'))
  displayName: Deploy to AKS demo

  jobs:

    - job: Validation 
      displayName: Manual validation job
      continueOnError: false
      pool: server
      timeoutInMinutes: 1440

      steps:
      - task: ManualValidation@0
        displayName: Manual Validation
        retryCountOnTaskFailure: 1
        timeoutInMinutes: 120
        inputs:
          notifyUsers: |
            nicolae.nicolaev@endava.com
            vitali.maximov@endava.com
          instructions: Please review and approve the fronend release

    - job: Deploy
      displayName: Deploy to demo-AKS job
      dependsOn: Validation
      pool: Default
    
      steps:
      - checkout: self
      
      - task: KubernetesManifest@0
        displayName: Deploy to Demo
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          manifests: manifests/demo-deployment.yml
          containers: mddinternship2021h2project.azurecr.io/grocery-shop-ui:$(buildTag)
    
      - task: Kubernetes@1
        displayName: check demo deployment status 

        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          command: 'rollout'
          arguments: 'status deployment/grocery-shop-ui'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'MDDInternship_GroceryList'
          azureContainerRegistry: 'mddinternship2021h2project.azurecr.io'
          forceUpdate: false

      - task: Kubernetes@1
        displayName: rollback to previous version
        condition: failed()

        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceEndpoint: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          command: 'rollout'
          arguments: 'undo deployment/grocery-shop-ui'
          secretType: 'dockerRegistry'
          containerRegistryType: 'Azure Container Registry'
          azureSubscriptionEndpointForSecrets: 'MDDInternship_GroceryList'
          azureContainerRegistry: 'mddinternship2021h2project.azurecr.io'
          forceUpdate: false
