variables:
  - group: grocery-list
  - name: BuildParameters.dockerFile
    value: '**/Dockerfile'
  # - name: vmImageName
  #   value: ubuntu-18.04
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isRelease
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/')]
  - name: isDevOps
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/devops/')]
  - name: isPR
    value: $[eq(variables['Build.Reason'], 'PullRequest')]
  
resources:
  pipelines:
  - pipeline: grocery-shop-ui
    source: grocery-shop-ui
    trigger:
      branches:
        include:
        - main
        - releases/*
  
name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)
  
stages:
  
- stage: Test_Build
  condition: and(eq(variables.isPR, 'true'), eq(variables.isMain, 'false'), eq(variables.isRelease, 'false'))
  displayName: 'Run build image'

  jobs:
  - job: Build
    displayName: Build job
    pool: Default
      # vmImage: $(vmImageName)
    steps:
    - checkout: self

    - task: Docker@0
      displayName: Clean previous images
      inputs:
        action: Run a Docker command
        customCommand: system prune -af

    - task: Docker@0
      displayName: Build an image
      inputs:
        dockerFile: $(BuildParameters.dockerFile)
        # buildArguments: SONAR_TOKEN=$(SONAR_TOKEN)
        additionalImageTags: $(Build.BuildId)
        includeLatestTag: true

- stage: Build_N_Push
  condition: or(eq(variables.isMain, 'true'), eq(variables.isDevOps, 'true'))
  displayName: 'Run build and push image to ACR'

  jobs:
  - job: Build
    displayName: Build_N_Push job
    pool: Default
      # vmImage: $(vmImageName)
    steps:
    - checkout: self

    - task: Docker@0
      displayName: Clean previous images
      inputs:
        action: Run a Docker command
        customCommand: system prune -af

    - task: Docker@0
      displayName: Build an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        dockerFile: $(BuildParameters.dockerFile)
        # buildArguments: SONAR_TOKEN=$(SONAR_TOKEN)
        imageName: grocery-shop-ui
        additionalImageTags: $(Build.BuildId)
        includeLatestTag: true

    - task: Docker@0
      displayName: Push an image
      inputs:
        azureSubscriptionEndpoint: 38386be4-ac4e-425b-8cd7-0127b8f9c0d9
        azureContainerRegistry: '{"loginServer":"mddinternship2021h2project.azurecr.io", "id" : "/subscriptions/01145a00-1779-4383-8b3a-08a39e3816fe/resourceGroups/Internship/providers/Microsoft.ContainerRegistry/registries/mddinternship2021h2project"}'
        action: Push an image
        imageName: grocery-shop-ui
        additionalImageTags: $(Build.BuildId)
        includeLatestTag: true

- stage: Deploy2dev
  dependsOn: Build_N_Push
  condition: or(eq(variables.isMain, 'true'), eq(variables.isDevOps, 'true'))
  displayName: Deploy to AKS dev

  jobs:
    - job: Deploy
      displayName: Deploy to dev-AKS job
      pool: Default
        # vmImage: $(vmImageName)
      
      steps:
      - checkout: self
      
      - task: KubernetesManifest@0
        displayName: Delete previous deployment
        inputs:
          action: delete
          arguments: deployment grocery-shop-ui
          kubernetesServiceConnection: 'grocery-list-dev-sc'
          namespace: 'grocery-list-dev'     
      
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'grocery-list-dev-sc'
          namespace: 'grocery-list-dev'
          manifests: manifests/dev-deployment.yml

- stage: Deploy2demo
  dependsOn: Build_N_Push
  condition: eq(variables.isRelease, 'true')
  displayName: Deploy to AKS demo

  jobs:
    - job: Deploy
      displayName: Deploy to demo-AKS job
      pool: Default
        # vmImage: $(vmImageName)
      
      steps:
      - checkout: self
      
      - task: KubernetesManifest@0
        displayName: Delete previous deployment
        inputs:
          action: delete
          arguments: deployment grocery-shop-ui
          kubernetesServiceConnection: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
      
      - task: KubernetesManifest@0
        displayName: deploy
        inputs:
          action: 'deploy'
          kubernetesServiceConnection: 'grocery-list-demo-sc'
          namespace: 'grocery-list-demo'
          manifests: manifests/demo-deployment.yml